const assert=require('node:assert/strict');const E=require('../engine.js');const make=n=>Array.from({length:n},(_,i)=>({id:'x'+i,en:'English '+i,es:'Una frase '+i}));const random=()=>.9999;
const all=make(12);let tests=0;function test(name,fn){fn();tests++;console.log('PASS '+name);}
test('first tap to match includes retries but excludes pauses',()=>{const s=E.createSession(all.slice(0,6),random);E.resume(s,1000);E.selectTimed(s,'en','x0',1200);E.pause(s,1400);E.resume(s,9000);const result=E.selectTimed(s,'es','x0',9300);assert.equal(result.record.ms,500);assert.equal(result.record.words,3);assert.equal(E.elapsed(s,9400),800);});
test('mismatch time is preserved until a correct pair is found',()=>{const s=E.createSession(all.slice(0,6),random);E.resume(s,1000);E.selectTimed(s,'en','x0',1100);E.selectTimed(s,'es','x1',1200);E.selectTimed(s,'en','x0',1400);const r=E.selectTimed(s,'es','x0',1800);assert.equal(r.record.ms,700);assert.equal(r.record.clean,false);assert.equal(s.attempts,2);});
test('replacement keeps six pairs with one occurrence per side',()=>{const s=E.createSession(all.slice(0,6),random);E.resume(s,1);E.selectTimed(s,'en','x0',2);E.selectTimed(s,'es','x0',3);const next=E.replacePair(s,'x0',all,{},random);assert.equal(next.id,'x6');assert.equal(s.items.length,6);assert.equal(s.left[0].id,'x6');assert.ok(!s.items.some(p=>p.id==='x0'));assert.deepEqual(s.left.map(p=>p.id).sort(),s.right.map(p=>p.id).sort());assert.equal(s.matches.length,1);});
test('same-round seen phrases never refill and retries take priority',()=>{const s=E.createSession(all.slice(0,6),random);E.resume(s,1);E.selectTimed(s,'en','x0',2);E.selectTimed(s,'es','x0',3);const next=E.replacePair(s,'x0',all,{x10:{needsReview:true,lastSeen:99}},random);assert.equal(next.id,'x10');assert.ok(s.seen.includes('x0'));});
test('replacement avoids duplicate answer strings',()=>{const pool=[...all,{id:'dup',en:'English 1',es:'different'}];const s=E.createSession(all.slice(0,6),random);E.resume(s,1);E.selectTimed(s,'en','x0',2);E.selectTimed(s,'es','x0',3);const next=E.replacePair(s,'x0',pool,{dup:{needsReview:true}},random);assert.notEqual(next.id,'dup');});
test('an exhausted set leaves complete remaining pairs',()=>{const s=E.createSession(all.slice(0,1),random);E.resume(s,1);E.selectTimed(s,'en','x0',2);E.selectTimed(s,'es','x0',3);assert.equal(E.replacePair(s,'x0',all.slice(0,1),{},random),null);assert.equal(s.items.length,0);assert.deepEqual(s.left,[null]);assert.deepEqual(s.right,[null]);});
test('paused and matched cards never create a second timed result',()=>{const s=E.createSession(all.slice(0,6),random);assert.equal(E.selectTimed(s,'en','x0',3).type,'ignored');E.resume(s,10);E.selectTimed(s,'en','x0',20);E.selectTimed(s,'es','x0',30);assert.equal(E.selectTimed(s,'es','x0',40).type,'ignored');assert.equal(s.matches.length,1);});
test('only six or more error-free matches shorten a round',()=>{assert.equal(E.nextLimit(60,6,6),55);assert.equal(E.nextLimit(60,10,10),55);assert.equal(E.nextLimit(60,6,7),60);assert.equal(E.nextLimit(60,5,5),60);assert.equal(E.nextLimit(20,8,8),20);assert.equal(E.nextLimit(25,6,6),20);});
console.log(tests+' continuous-play tests passed.');
